spring:
  profiles:
    active: dev
logging:
  level:
    root: INFO

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PWD}

---